title: Hemanth C # your name (or website title) here
logo: "/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Java and Web development Enthusiasist
  <br><br>
  <a href="mailto:hemanthrajcshy8055@gmail.com">hemanthrajcshy8055@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/hemanth-c-293367211/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/Hemanth-Hemu">Gihub</a> 
theme: jekyll-theme-minimal
